package analysis

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Event) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Signature":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Signature")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Signature")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SourceIP":
					z.Signature.SourceIP, err = dc.ReadUint32()
					if err != nil {
						err = msgp.WrapError(err, "Signature", "SourceIP")
						return
					}
				case "Port":
					z.Signature.Port, err = dc.ReadUint16()
					if err != nil {
						err = msgp.WrapError(err, "Signature", "Port")
						return
					}
				case "Traffic":
					err = z.Signature.Traffic.DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Signature", "Traffic")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Signature")
						return
					}
				}
			}
		case "Packets":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Packets")
					return
				}
				z.Packets = nil
			} else {
				if z.Packets == nil {
					z.Packets = new(EventPackets)
				}
				err = z.Packets.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Packets")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Event) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Signature"
	err = en.Append(0x82, 0xa9, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65)
	if err != nil {
		return
	}
	// map header, size 3
	// write "SourceIP"
	err = en.Append(0x83, 0xa8, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.Signature.SourceIP)
	if err != nil {
		err = msgp.WrapError(err, "Signature", "SourceIP")
		return
	}
	// write "Port"
	err = en.Append(0xa4, 0x50, 0x6f, 0x72, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Signature.Port)
	if err != nil {
		err = msgp.WrapError(err, "Signature", "Port")
		return
	}
	// write "Traffic"
	err = en.Append(0xa7, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63)
	if err != nil {
		return
	}
	err = z.Signature.Traffic.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Signature", "Traffic")
		return
	}
	// write "Packets"
	err = en.Append(0xa7, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73)
	if err != nil {
		return
	}
	if z.Packets == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.Packets.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Packets")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Event) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Signature"
	o = append(o, 0x82, 0xa9, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65)
	// map header, size 3
	// string "SourceIP"
	o = append(o, 0x83, 0xa8, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50)
	o = msgp.AppendUint32(o, z.Signature.SourceIP)
	// string "Port"
	o = append(o, 0xa4, 0x50, 0x6f, 0x72, 0x74)
	o = msgp.AppendUint16(o, z.Signature.Port)
	// string "Traffic"
	o = append(o, 0xa7, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63)
	o, err = z.Signature.Traffic.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Signature", "Traffic")
		return
	}
	// string "Packets"
	o = append(o, 0xa7, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73)
	if z.Packets == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.Packets.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Packets")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Event) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Signature":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Signature")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Signature")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SourceIP":
					z.Signature.SourceIP, bts, err = msgp.ReadUint32Bytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Signature", "SourceIP")
						return
					}
				case "Port":
					z.Signature.Port, bts, err = msgp.ReadUint16Bytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Signature", "Port")
						return
					}
				case "Traffic":
					bts, err = z.Signature.Traffic.UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Signature", "Traffic")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Signature")
						return
					}
				}
			}
		case "Packets":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Packets = nil
			} else {
				if z.Packets == nil {
					z.Packets = new(EventPackets)
				}
				bts, err = z.Packets.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Packets")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Event) Msgsize() (s int) {
	s = 1 + 10 + 1 + 9 + msgp.Uint32Size + 5 + msgp.Uint16Size + 8 + z.Signature.Traffic.Msgsize() + 8
	if z.Packets == nil {
		s += msgp.NilSize
	} else {
		s += z.Packets.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *EventPackets) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "First":
			z.First, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "First")
				return
			}
		case "Latest":
			z.Latest, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "Latest")
				return
			}
		case "Packets":
			z.Packets, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Packets")
				return
			}
		case "Bytes":
			z.Bytes, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
		case "Samples":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Samples")
				return
			}
			if cap(z.Samples) >= int(zb0002) {
				z.Samples = (z.Samples)[:zb0002]
			} else {
				z.Samples = make([][]byte, zb0002)
			}
			for za0001 := range z.Samples {
				z.Samples[za0001], err = dc.ReadBytes(z.Samples[za0001])
				if err != nil {
					err = msgp.WrapError(err, "Samples", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *EventPackets) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "First"
	err = en.Append(0x85, 0xa5, 0x46, 0x69, 0x72, 0x73, 0x74)
	if err != nil {
		return
	}
	err = en.WriteTime(z.First)
	if err != nil {
		err = msgp.WrapError(err, "First")
		return
	}
	// write "Latest"
	err = en.Append(0xa6, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74)
	if err != nil {
		return
	}
	err = en.WriteTime(z.Latest)
	if err != nil {
		err = msgp.WrapError(err, "Latest")
		return
	}
	// write "Packets"
	err = en.Append(0xa7, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Packets)
	if err != nil {
		err = msgp.WrapError(err, "Packets")
		return
	}
	// write "Bytes"
	err = en.Append(0xa5, 0x42, 0x79, 0x74, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Bytes)
	if err != nil {
		err = msgp.WrapError(err, "Bytes")
		return
	}
	// write "Samples"
	err = en.Append(0xa7, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Samples)))
	if err != nil {
		err = msgp.WrapError(err, "Samples")
		return
	}
	for za0001 := range z.Samples {
		err = en.WriteBytes(z.Samples[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Samples", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *EventPackets) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "First"
	o = append(o, 0x85, 0xa5, 0x46, 0x69, 0x72, 0x73, 0x74)
	o = msgp.AppendTime(o, z.First)
	// string "Latest"
	o = append(o, 0xa6, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74)
	o = msgp.AppendTime(o, z.Latest)
	// string "Packets"
	o = append(o, 0xa7, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73)
	o = msgp.AppendUint64(o, z.Packets)
	// string "Bytes"
	o = append(o, 0xa5, 0x42, 0x79, 0x74, 0x65, 0x73)
	o = msgp.AppendUint64(o, z.Bytes)
	// string "Samples"
	o = append(o, 0xa7, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Samples)))
	for za0001 := range z.Samples {
		o = msgp.AppendBytes(o, z.Samples[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EventPackets) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "First":
			z.First, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "First")
				return
			}
		case "Latest":
			z.Latest, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Latest")
				return
			}
		case "Packets":
			z.Packets, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Packets")
				return
			}
		case "Bytes":
			z.Bytes, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
		case "Samples":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Samples")
				return
			}
			if cap(z.Samples) >= int(zb0002) {
				z.Samples = (z.Samples)[:zb0002]
			} else {
				z.Samples = make([][]byte, zb0002)
			}
			for za0001 := range z.Samples {
				z.Samples[za0001], bts, err = msgp.ReadBytesBytes(bts, z.Samples[za0001])
				if err != nil {
					err = msgp.WrapError(err, "Samples", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *EventPackets) Msgsize() (s int) {
	s = 1 + 6 + msgp.TimeSize + 7 + msgp.TimeSize + 8 + msgp.Uint64Size + 6 + msgp.Uint64Size + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Samples {
		s += msgp.BytesPrefixSize + len(z.Samples[za0001])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *EventSignature) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SourceIP":
			z.SourceIP, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "SourceIP")
				return
			}
		case "Port":
			z.Port, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "Traffic":
			err = z.Traffic.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Traffic")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *EventSignature) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "SourceIP"
	err = en.Append(0x83, 0xa8, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.SourceIP)
	if err != nil {
		err = msgp.WrapError(err, "SourceIP")
		return
	}
	// write "Port"
	err = en.Append(0xa4, 0x50, 0x6f, 0x72, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Port)
	if err != nil {
		err = msgp.WrapError(err, "Port")
		return
	}
	// write "Traffic"
	err = en.Append(0xa7, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63)
	if err != nil {
		return
	}
	err = z.Traffic.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Traffic")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *EventSignature) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "SourceIP"
	o = append(o, 0x83, 0xa8, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50)
	o = msgp.AppendUint32(o, z.SourceIP)
	// string "Port"
	o = append(o, 0xa4, 0x50, 0x6f, 0x72, 0x74)
	o = msgp.AppendUint16(o, z.Port)
	// string "Traffic"
	o = append(o, 0xa7, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63)
	o, err = z.Traffic.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Traffic")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EventSignature) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SourceIP":
			z.SourceIP, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SourceIP")
				return
			}
		case "Port":
			z.Port, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "Traffic":
			bts, err = z.Traffic.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Traffic")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *EventSignature) Msgsize() (s int) {
	s = 1 + 9 + msgp.Uint32Size + 5 + msgp.Uint16Size + 8 + z.Traffic.Msgsize()
	return
}
