package analysis

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"darknet-events/internal/set"

	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Event) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Source":
			err = z.Source.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Source")
				return
			}
		case "Packets":
			err = z.Packets.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Packets")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Event) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Source"
	err = en.Append(0x82, 0xa6, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65)
	if err != nil {
		return
	}
	err = z.Source.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Source")
		return
	}
	// write "Packets"
	err = en.Append(0xa7, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73)
	if err != nil {
		return
	}
	err = z.Packets.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Packets")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Event) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Source"
	o = append(o, 0x82, 0xa6, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65)
	o, err = z.Source.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Source")
		return
	}
	// string "Packets"
	o = append(o, 0xa7, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73)
	o, err = z.Packets.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Packets")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Event) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Source":
			bts, err = z.Source.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Source")
				return
			}
		case "Packets":
			bts, err = z.Packets.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Packets")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Event) Msgsize() (s int) {
	s = 1 + 7 + z.Source.Msgsize() + 8 + z.Packets.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *EventPacketsIPv4) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "DestIPv4":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "DestIPv4")
					return
				}
				z.DestIPv4 = nil
			} else {
				if z.DestIPv4 == nil {
					z.DestIPv4 = new(set.Uint32Set)
				}
				err = z.DestIPv4.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "DestIPv4")
					return
				}
			}
		case "First":
			z.First, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "First")
				return
			}
		case "Latest":
			z.Latest, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "Latest")
				return
			}
		case "Packets":
			z.Packets, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Packets")
				return
			}
		case "Bytes":
			z.Bytes, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
		case "Samples":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Samples")
				return
			}
			if cap(z.Samples) >= int(zb0002) {
				z.Samples = (z.Samples)[:zb0002]
			} else {
				z.Samples = make([][]byte, zb0002)
			}
			for za0001 := range z.Samples {
				z.Samples[za0001], err = dc.ReadBytes(z.Samples[za0001])
				if err != nil {
					err = msgp.WrapError(err, "Samples", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *EventPacketsIPv4) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 6
	// write "DestIPv4"
	err = en.Append(0x86, 0xa8, 0x44, 0x65, 0x73, 0x74, 0x49, 0x50, 0x76, 0x34)
	if err != nil {
		return
	}
	if z.DestIPv4 == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.DestIPv4.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "DestIPv4")
			return
		}
	}
	// write "First"
	err = en.Append(0xa5, 0x46, 0x69, 0x72, 0x73, 0x74)
	if err != nil {
		return
	}
	err = en.WriteTime(z.First)
	if err != nil {
		err = msgp.WrapError(err, "First")
		return
	}
	// write "Latest"
	err = en.Append(0xa6, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74)
	if err != nil {
		return
	}
	err = en.WriteTime(z.Latest)
	if err != nil {
		err = msgp.WrapError(err, "Latest")
		return
	}
	// write "Packets"
	err = en.Append(0xa7, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Packets)
	if err != nil {
		err = msgp.WrapError(err, "Packets")
		return
	}
	// write "Bytes"
	err = en.Append(0xa5, 0x42, 0x79, 0x74, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Bytes)
	if err != nil {
		err = msgp.WrapError(err, "Bytes")
		return
	}
	// write "Samples"
	err = en.Append(0xa7, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Samples)))
	if err != nil {
		err = msgp.WrapError(err, "Samples")
		return
	}
	for za0001 := range z.Samples {
		err = en.WriteBytes(z.Samples[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Samples", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *EventPacketsIPv4) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 6
	// string "DestIPv4"
	o = append(o, 0x86, 0xa8, 0x44, 0x65, 0x73, 0x74, 0x49, 0x50, 0x76, 0x34)
	if z.DestIPv4 == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.DestIPv4.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "DestIPv4")
			return
		}
	}
	// string "First"
	o = append(o, 0xa5, 0x46, 0x69, 0x72, 0x73, 0x74)
	o = msgp.AppendTime(o, z.First)
	// string "Latest"
	o = append(o, 0xa6, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74)
	o = msgp.AppendTime(o, z.Latest)
	// string "Packets"
	o = append(o, 0xa7, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73)
	o = msgp.AppendUint64(o, z.Packets)
	// string "Bytes"
	o = append(o, 0xa5, 0x42, 0x79, 0x74, 0x65, 0x73)
	o = msgp.AppendUint64(o, z.Bytes)
	// string "Samples"
	o = append(o, 0xa7, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Samples)))
	for za0001 := range z.Samples {
		o = msgp.AppendBytes(o, z.Samples[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EventPacketsIPv4) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "DestIPv4":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.DestIPv4 = nil
			} else {
				if z.DestIPv4 == nil {
					z.DestIPv4 = new(set.Uint32Set)
				}
				bts, err = z.DestIPv4.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "DestIPv4")
					return
				}
			}
		case "First":
			z.First, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "First")
				return
			}
		case "Latest":
			z.Latest, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Latest")
				return
			}
		case "Packets":
			z.Packets, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Packets")
				return
			}
		case "Bytes":
			z.Bytes, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
		case "Samples":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Samples")
				return
			}
			if cap(z.Samples) >= int(zb0002) {
				z.Samples = (z.Samples)[:zb0002]
			} else {
				z.Samples = make([][]byte, zb0002)
			}
			for za0001 := range z.Samples {
				z.Samples[za0001], bts, err = msgp.ReadBytesBytes(bts, z.Samples[za0001])
				if err != nil {
					err = msgp.WrapError(err, "Samples", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *EventPacketsIPv4) Msgsize() (s int) {
	s = 1 + 9
	if z.DestIPv4 == nil {
		s += msgp.NilSize
	} else {
		s += z.DestIPv4.Msgsize()
	}
	s += 6 + msgp.TimeSize + 7 + msgp.TimeSize + 8 + msgp.Uint64Size + 6 + msgp.Uint64Size + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Samples {
		s += msgp.BytesPrefixSize + len(z.Samples[za0001])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *EventPacketsIPv6) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ipv6addr":
			err = dc.ReadExtension(&z.DestIPv6)
			if err != nil {
				err = msgp.WrapError(err, "DestIPv6")
				return
			}
		case "First":
			z.First, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "First")
				return
			}
		case "Latest":
			z.Latest, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "Latest")
				return
			}
		case "Packets":
			z.Packets, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Packets")
				return
			}
		case "Bytes":
			z.Bytes, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
		case "Samples":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Samples")
				return
			}
			if cap(z.Samples) >= int(zb0002) {
				z.Samples = (z.Samples)[:zb0002]
			} else {
				z.Samples = make([][]byte, zb0002)
			}
			for za0001 := range z.Samples {
				z.Samples[za0001], err = dc.ReadBytes(z.Samples[za0001])
				if err != nil {
					err = msgp.WrapError(err, "Samples", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *EventPacketsIPv6) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 6
	// write "ipv6addr"
	err = en.Append(0x86, 0xa8, 0x69, 0x70, 0x76, 0x36, 0x61, 0x64, 0x64, 0x72)
	if err != nil {
		return
	}
	err = en.WriteExtension(&z.DestIPv6)
	if err != nil {
		err = msgp.WrapError(err, "DestIPv6")
		return
	}
	// write "First"
	err = en.Append(0xa5, 0x46, 0x69, 0x72, 0x73, 0x74)
	if err != nil {
		return
	}
	err = en.WriteTime(z.First)
	if err != nil {
		err = msgp.WrapError(err, "First")
		return
	}
	// write "Latest"
	err = en.Append(0xa6, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74)
	if err != nil {
		return
	}
	err = en.WriteTime(z.Latest)
	if err != nil {
		err = msgp.WrapError(err, "Latest")
		return
	}
	// write "Packets"
	err = en.Append(0xa7, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Packets)
	if err != nil {
		err = msgp.WrapError(err, "Packets")
		return
	}
	// write "Bytes"
	err = en.Append(0xa5, 0x42, 0x79, 0x74, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Bytes)
	if err != nil {
		err = msgp.WrapError(err, "Bytes")
		return
	}
	// write "Samples"
	err = en.Append(0xa7, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Samples)))
	if err != nil {
		err = msgp.WrapError(err, "Samples")
		return
	}
	for za0001 := range z.Samples {
		err = en.WriteBytes(z.Samples[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Samples", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *EventPacketsIPv6) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 6
	// string "ipv6addr"
	o = append(o, 0x86, 0xa8, 0x69, 0x70, 0x76, 0x36, 0x61, 0x64, 0x64, 0x72)
	o, err = msgp.AppendExtension(o, &z.DestIPv6)
	if err != nil {
		err = msgp.WrapError(err, "DestIPv6")
		return
	}
	// string "First"
	o = append(o, 0xa5, 0x46, 0x69, 0x72, 0x73, 0x74)
	o = msgp.AppendTime(o, z.First)
	// string "Latest"
	o = append(o, 0xa6, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74)
	o = msgp.AppendTime(o, z.Latest)
	// string "Packets"
	o = append(o, 0xa7, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73)
	o = msgp.AppendUint64(o, z.Packets)
	// string "Bytes"
	o = append(o, 0xa5, 0x42, 0x79, 0x74, 0x65, 0x73)
	o = msgp.AppendUint64(o, z.Bytes)
	// string "Samples"
	o = append(o, 0xa7, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Samples)))
	for za0001 := range z.Samples {
		o = msgp.AppendBytes(o, z.Samples[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EventPacketsIPv6) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ipv6addr":
			bts, err = msgp.ReadExtensionBytes(bts, &z.DestIPv6)
			if err != nil {
				err = msgp.WrapError(err, "DestIPv6")
				return
			}
		case "First":
			z.First, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "First")
				return
			}
		case "Latest":
			z.Latest, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Latest")
				return
			}
		case "Packets":
			z.Packets, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Packets")
				return
			}
		case "Bytes":
			z.Bytes, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
		case "Samples":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Samples")
				return
			}
			if cap(z.Samples) >= int(zb0002) {
				z.Samples = (z.Samples)[:zb0002]
			} else {
				z.Samples = make([][]byte, zb0002)
			}
			for za0001 := range z.Samples {
				z.Samples[za0001], bts, err = msgp.ReadBytesBytes(bts, z.Samples[za0001])
				if err != nil {
					err = msgp.WrapError(err, "Samples", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *EventPacketsIPv6) Msgsize() (s int) {
	s = 1 + 9 + msgp.ExtensionPrefixSize + z.DestIPv6.Len() + 6 + msgp.TimeSize + 7 + msgp.TimeSize + 8 + msgp.Uint64Size + 6 + msgp.Uint64Size + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Samples {
		s += msgp.BytesPrefixSize + len(z.Samples[za0001])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *EventSignatureIPv4) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SourceIPv4":
			z.SourceIPv4, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "SourceIPv4")
				return
			}
		case "Port":
			z.Port, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "Traffic":
			err = z.Traffic.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Traffic")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *EventSignatureIPv4) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "SourceIPv4"
	err = en.Append(0x83, 0xaa, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x76, 0x34)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.SourceIPv4)
	if err != nil {
		err = msgp.WrapError(err, "SourceIPv4")
		return
	}
	// write "Port"
	err = en.Append(0xa4, 0x50, 0x6f, 0x72, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Port)
	if err != nil {
		err = msgp.WrapError(err, "Port")
		return
	}
	// write "Traffic"
	err = en.Append(0xa7, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63)
	if err != nil {
		return
	}
	err = z.Traffic.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Traffic")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *EventSignatureIPv4) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "SourceIPv4"
	o = append(o, 0x83, 0xaa, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x76, 0x34)
	o = msgp.AppendUint32(o, z.SourceIPv4)
	// string "Port"
	o = append(o, 0xa4, 0x50, 0x6f, 0x72, 0x74)
	o = msgp.AppendUint16(o, z.Port)
	// string "Traffic"
	o = append(o, 0xa7, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63)
	o, err = z.Traffic.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Traffic")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EventSignatureIPv4) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SourceIPv4":
			z.SourceIPv4, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SourceIPv4")
				return
			}
		case "Port":
			z.Port, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "Traffic":
			bts, err = z.Traffic.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Traffic")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *EventSignatureIPv4) Msgsize() (s int) {
	s = 1 + 11 + msgp.Uint32Size + 5 + msgp.Uint16Size + 8 + z.Traffic.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *EventSignatureIPv6) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ipv6addr":
			err = dc.ReadExtension(&z.SourceIPv6)
			if err != nil {
				err = msgp.WrapError(err, "SourceIPv6")
				return
			}
		case "Port":
			z.Port, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "Traffic":
			err = z.Traffic.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Traffic")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *EventSignatureIPv6) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "ipv6addr"
	err = en.Append(0x83, 0xa8, 0x69, 0x70, 0x76, 0x36, 0x61, 0x64, 0x64, 0x72)
	if err != nil {
		return
	}
	err = en.WriteExtension(&z.SourceIPv6)
	if err != nil {
		err = msgp.WrapError(err, "SourceIPv6")
		return
	}
	// write "Port"
	err = en.Append(0xa4, 0x50, 0x6f, 0x72, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Port)
	if err != nil {
		err = msgp.WrapError(err, "Port")
		return
	}
	// write "Traffic"
	err = en.Append(0xa7, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63)
	if err != nil {
		return
	}
	err = z.Traffic.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Traffic")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *EventSignatureIPv6) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "ipv6addr"
	o = append(o, 0x83, 0xa8, 0x69, 0x70, 0x76, 0x36, 0x61, 0x64, 0x64, 0x72)
	o, err = msgp.AppendExtension(o, &z.SourceIPv6)
	if err != nil {
		err = msgp.WrapError(err, "SourceIPv6")
		return
	}
	// string "Port"
	o = append(o, 0xa4, 0x50, 0x6f, 0x72, 0x74)
	o = msgp.AppendUint16(o, z.Port)
	// string "Traffic"
	o = append(o, 0xa7, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63)
	o, err = z.Traffic.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Traffic")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EventSignatureIPv6) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ipv6addr":
			bts, err = msgp.ReadExtensionBytes(bts, &z.SourceIPv6)
			if err != nil {
				err = msgp.WrapError(err, "SourceIPv6")
				return
			}
		case "Port":
			z.Port, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "Traffic":
			bts, err = z.Traffic.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Traffic")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *EventSignatureIPv6) Msgsize() (s int) {
	s = 1 + 9 + msgp.ExtensionPrefixSize + z.SourceIPv6.Len() + 5 + msgp.Uint16Size + 8 + z.Traffic.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *EventSourceIPv4) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SourceIPv4":
			z.SourceIPv4, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "SourceIPv4")
				return
			}
		case "Port":
			z.Port, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "Traffic":
			err = z.Traffic.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Traffic")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *EventSourceIPv4) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "SourceIPv4"
	err = en.Append(0x83, 0xaa, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x76, 0x34)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.SourceIPv4)
	if err != nil {
		err = msgp.WrapError(err, "SourceIPv4")
		return
	}
	// write "Port"
	err = en.Append(0xa4, 0x50, 0x6f, 0x72, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Port)
	if err != nil {
		err = msgp.WrapError(err, "Port")
		return
	}
	// write "Traffic"
	err = en.Append(0xa7, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63)
	if err != nil {
		return
	}
	err = z.Traffic.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Traffic")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *EventSourceIPv4) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "SourceIPv4"
	o = append(o, 0x83, 0xaa, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x76, 0x34)
	o = msgp.AppendUint32(o, z.SourceIPv4)
	// string "Port"
	o = append(o, 0xa4, 0x50, 0x6f, 0x72, 0x74)
	o = msgp.AppendUint16(o, z.Port)
	// string "Traffic"
	o = append(o, 0xa7, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63)
	o, err = z.Traffic.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Traffic")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EventSourceIPv4) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SourceIPv4":
			z.SourceIPv4, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SourceIPv4")
				return
			}
		case "Port":
			z.Port, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "Traffic":
			bts, err = z.Traffic.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Traffic")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *EventSourceIPv4) Msgsize() (s int) {
	s = 1 + 11 + msgp.Uint32Size + 5 + msgp.Uint16Size + 8 + z.Traffic.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *EventSourceIPv6) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ipv6addr":
			err = dc.ReadExtension(&z.SourceIPv6)
			if err != nil {
				err = msgp.WrapError(err, "SourceIPv6")
				return
			}
		case "Port":
			z.Port, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "Traffic":
			err = z.Traffic.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Traffic")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *EventSourceIPv6) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "ipv6addr"
	err = en.Append(0x83, 0xa8, 0x69, 0x70, 0x76, 0x36, 0x61, 0x64, 0x64, 0x72)
	if err != nil {
		return
	}
	err = en.WriteExtension(&z.SourceIPv6)
	if err != nil {
		err = msgp.WrapError(err, "SourceIPv6")
		return
	}
	// write "Port"
	err = en.Append(0xa4, 0x50, 0x6f, 0x72, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Port)
	if err != nil {
		err = msgp.WrapError(err, "Port")
		return
	}
	// write "Traffic"
	err = en.Append(0xa7, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63)
	if err != nil {
		return
	}
	err = z.Traffic.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Traffic")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *EventSourceIPv6) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "ipv6addr"
	o = append(o, 0x83, 0xa8, 0x69, 0x70, 0x76, 0x36, 0x61, 0x64, 0x64, 0x72)
	o, err = msgp.AppendExtension(o, &z.SourceIPv6)
	if err != nil {
		err = msgp.WrapError(err, "SourceIPv6")
		return
	}
	// string "Port"
	o = append(o, 0xa4, 0x50, 0x6f, 0x72, 0x74)
	o = msgp.AppendUint16(o, z.Port)
	// string "Traffic"
	o = append(o, 0xa7, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63)
	o, err = z.Traffic.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Traffic")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EventSourceIPv6) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ipv6addr":
			bts, err = msgp.ReadExtensionBytes(bts, &z.SourceIPv6)
			if err != nil {
				err = msgp.WrapError(err, "SourceIPv6")
				return
			}
		case "Port":
			z.Port, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "Traffic":
			bts, err = z.Traffic.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Traffic")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *EventSourceIPv6) Msgsize() (s int) {
	s = 1 + 9 + msgp.ExtensionPrefixSize + z.SourceIPv6.Len() + 5 + msgp.Uint16Size + 8 + z.Traffic.Msgsize()
	return
}
